//! Create a multi-sheet workbook with shared strings, merges, and a formula.

use officexml::packaging::{SpreadsheetDocument, SpreadsheetDocumentType};

fn main() -> officexml::Result<()> {
    let path = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "report.xlsx".into());

    let mut doc = SpreadsheetDocument::create(&path, SpreadsheetDocumentType::Workbook)?;

    doc.write_sheet_shared_strings(
        "Sales",
        &[
            vec!["Region", "Q1", "Q2", "Total"],
            vec!["North", "100", "120", ""],
            vec!["South", "80", "95", ""],
        ],
    )?;
    doc.set_merge_cells("Sales", &["A1:A1"])?; // no-op style demo; real merge:
    doc.set_merge_cells("Sales", &[])?; // clear
    // Title-style merge on a header we add via formula sheet
    doc.set_column_widths("Sales", &[(1, 1, 14.0), (2, 4, 10.0)])?;
    doc.set_cell_formula("Sales", "D2", "B2+C2", Some("220"))?;
    doc.set_cell_formula("Sales", "D3", "B3+C3", Some("175"))?;
    doc.add_minimal_styles(true)?;

    doc.write_sheet_strings("Notes", &[vec!["Generated by openxml-rs"]])?;

    doc.set_title("Sales Report")?;
    doc.set_creator("openxml-rs")?;
    doc.save()?;
    println!("Wrote {path}");
    println!("Sheets: {:?}", doc.worksheets().iter().map(|s| &s.name).collect::<Vec<_>>());
    Ok(())
}
